/**
 * Derives how much of a scene's progress each shot and beat occupies.
 *
 * The mapping file carries staging weights; the text carries reading load. This
 * module is the only implementation of the formula in the browser, and
 * `scripts/show-scene.py --plan --json` produces the fixture that proves it still
 * agrees with the reference. See docs/text-experience-binding.md §4.
 */

import type { ExperienceSceneFile } from '../types/schema.ts';

/** A beat is held at least this long, in segment-equivalents, so a textless beat still reads. */
export const MINIMUM_HOLD = 1;

// Shapes come from the schemas, so a schema change is a type error rather than a
// silent disagreement. See src/types/schema.ts, generated by npm run types:schema.
export type SceneMapping = ExperienceSceneFile;
export type ShotMapping = SceneMapping['shots'][number];
export type BeatMapping = ShotMapping['beats'][number];

export interface Span {
  id: string;
  start: number;
  end: number;
}

export interface ScenePlan {
  scene: string;
  locale: string;
  shots: Span[];
  beats: Span[];
  /** Characters of staged text in this locale. An authoring statistic, never a scroll multiplier. */
  characters: number;
  /**
   * Mean staged sentence length in this locale: one segment-equivalent.
   *
   * `null` when the scene stages no text at all. Such a scene has no reading load,
   * so there is no average to take; every beat then costs its weight times the
   * minimum hold. See docs/text-experience-binding.md §4.
   */
  mean: number | null;
}

const weightOf = (unit: { weight?: number }): number => unit.weight ?? 1;

function stagedSegments(scene: SceneMapping): string[] {
  return scene.shots.flatMap((shot) => shot.beats.flatMap((beat) => beat.segments));
}

function lengthOf(segments: string[], text: Readonly<Record<string, string>>): number {
  return segments.reduce((total, id) => {
    const sentence = text[id];
    if (sentence === undefined) {
      throw new Error(`segment ${id} has no text in this locale`);
    }
    return total + [...sentence].length;
  }, 0);
}

function spansFrom(costs: { id: string; cost: number }[], total: number): Span[] {
  let start = 0;
  return costs.map(({ id, cost }) => {
    const end = start + cost / total;
    const span = { id, start, end };
    start = end;
    return span;
  });
}

/**
 * Shot and beat spans for one locale.
 *
 * Normalizing by this locale's own mean sentence length keeps the shape of the
 * plan comparable between languages. Absolute length stays out of it: total scroll
 * distance is art-directed, not derived from a character count.
 */
export function planScene(
  scene: SceneMapping,
  locale: string,
  text: Readonly<Record<string, string>>,
): ScenePlan {
  const staged = stagedSegments(scene);
  const characters = lengthOf(staged, text);
  // A scene may legitimately stage no text: the model lets a beat hold 0 segments,
  // and a purely visual scene is that all the way up. It carries no reading load, so
  // it has no mean, and its beats fall back to the minimum hold below.
  const mean = staged.length === 0 ? null : characters / staged.length;

  const beatCosts: { id: string; cost: number }[] = [];
  const shotCosts: { id: string; cost: number }[] = [];

  for (const shot of scene.shots) {
    const shotWeight = weightOf(shot);
    let shotTotal = 0;
    for (const beat of shot.beats) {
      const load = mean === null ? 0 : lengthOf(beat.segments, text) / mean;
      const cost = weightOf(beat) * Math.max(load, MINIMUM_HOLD);
      shotTotal += cost;
      // A beat divides its own shot's span, so it carries the shot's weight too.
      beatCosts.push({ id: beat.id, cost: cost * shotWeight });
    }
    shotCosts.push({ id: shot.id, cost: shotWeight * shotTotal });
  }

  const total = shotCosts.reduce((sum, shot) => sum + shot.cost, 0);

  return {
    scene: scene.id,
    locale,
    shots: spansFrom(shotCosts, total),
    beats: spansFrom(beatCosts, total),
    characters,
    mean,
  };
}

/**
 * The overlap each shot carries into the next, in shot order, validated.
 *
 * Overlap is progress-neutral: nothing above reads it, so a scene's spans are the
 * same whether its shots overlap or not, and adding one to a mapping cannot move a
 * boundary, change a beat's owner, or lengthen the scene. It is read here only
 * because the build has to write it into the markup.
 *
 * The invariant lives on both sides of the boundary on purpose.
 * `scripts/check-experience.py` refuses a bad mapping in the data gate, and this
 * refuses one during a build, which is the half a remote build without the Python
 * checkers actually runs.
 */
export function overlapsOf(scene: SceneMapping): number[] {
  const last = scene.shots.length - 1;
  return scene.shots.map((shot, index) => {
    const overlap = shot.overlap ?? 0;
    if (index === last && overlap !== 0) {
      throw new Error(
        `${scene.id}: the last shot ${shot.id} declares an overlap of ${overlap}, ` +
          'but it has no following shot to hand over to',
      );
    }
    if (!(overlap >= 0 && overlap <= 1)) {
      throw new Error(`${scene.id}: shot ${shot.id} has an overlap outside 0..1: ${overlap}`);
    }
    return overlap;
  });
}
