/**
 * Generated by scripts/bake-art.mjs (`npm run art:bake`); do not edit by hand.
 * The registry's vectors rendered through the engraved treatment: whole figures
 * (BAKED), and figures whose parts a demo moves as cut-outs, the drawing without the
 * parts and each part alone in the same box (BAKED_PARTS). A picture that shows
 * Alice's colours has one file per Alice variant. See docs/art-trials.md.
 */

import type { ImageSource } from './registry.ts';

type Sources = Partial<Record<'blue' | 'yellow' | 'any', ImageSource>>;

export const BAKED: Record<string, Sources> = {
  'alice/falling': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--falling.yellow.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--falling.blue.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
  },
  'alice/running-away': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--running-away.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--running-away.blue.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
  },
  'alice/from-behind': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--from-behind.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--from-behind.blue.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
  },
  'alice/looking-down': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--looking-down.yellow.webp', import.meta.url)
        .href,
      width: 800,
      height: 440,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--looking-down.blue.webp', import.meta.url)
        .href,
      width: 800,
      height: 440,
    },
  },
  'alice/foot': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--foot.yellow.webp', import.meta.url).href,
      width: 400,
      height: 520,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--foot.blue.webp', import.meta.url).href,
      width: 400,
      height: 520,
    },
  },
  'alice/hand-left': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--hand-left.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 400,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--hand-left.blue.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
  },
  'alice/hand-right': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--hand-right.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 400,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--hand-right.blue.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
  },
  'alice/standing': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--standing.yellow.webp', import.meta.url).href,
      width: 160,
      height: 220,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--standing.blue.webp', import.meta.url).href,
      width: 160,
      height: 220,
    },
  },
  'alice/kneeling': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--kneeling.yellow.webp', import.meta.url).href,
      width: 460,
      height: 460,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--kneeling.blue.webp', import.meta.url).href,
      width: 460,
      height: 460,
    },
  },
  'alice/filling': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--filling.yellow.webp', import.meta.url).href,
      width: 1440,
      height: 660,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--filling.blue.webp', import.meta.url).href,
      width: 1440,
      height: 660,
    },
  },
  'white-rabbit/herald': {
    any: {
      src: new URL('../../assets/images/figures/white-rabbit--herald.any.webp', import.meta.url)
        .href,
      width: 280,
      height: 440,
    },
  },
  'white-rabbit/garden': {
    any: {
      src: new URL('../../assets/images/figures/white-rabbit--garden.any.webp', import.meta.url)
        .href,
      width: 120,
      height: 160,
    },
  },
  'queen-of-hearts': {
    any: {
      src: new URL('../../assets/images/figures/queen-of-hearts.any.webp', import.meta.url).href,
      width: 320,
      height: 480,
    },
  },
  'king-of-hearts': {
    any: {
      src: new URL('../../assets/images/figures/king-of-hearts.any.webp', import.meta.url).href,
      width: 320,
      height: 480,
    },
  },
  'knave-of-hearts': {
    any: {
      src: new URL('../../assets/images/figures/knave-of-hearts.any.webp', import.meta.url).href,
      width: 280,
      height: 440,
    },
  },
  'card-soldier': {
    any: {
      src: new URL('../../assets/images/figures/card-soldier.any.webp', import.meta.url).href,
      width: 240,
      height: 440,
    },
  },
  'card-arch': {
    any: {
      src: new URL('../../assets/images/figures/card-arch.any.webp', import.meta.url).href,
      width: 400,
      height: 280,
    },
  },
  duchess: {
    any: {
      src: new URL('../../assets/images/figures/duchess.any.webp', import.meta.url).href,
      width: 480,
      height: 520,
    },
  },
  cook: {
    any: {
      src: new URL('../../assets/images/figures/cook.any.webp', import.meta.url).href,
      width: 400,
      height: 520,
    },
  },
  'march-hare': {
    any: {
      src: new URL('../../assets/images/figures/march-hare.any.webp', import.meta.url).href,
      width: 320,
      height: 520,
    },
  },
  dormouse: {
    any: {
      src: new URL('../../assets/images/figures/dormouse.any.webp', import.meta.url).href,
      width: 280,
      height: 220,
    },
  },
  'mock-turtle': {
    any: {
      src: new URL('../../assets/images/figures/mock-turtle.any.webp', import.meta.url).href,
      width: 480,
      height: 440,
    },
  },
  gryphon: {
    any: {
      src: new URL('../../assets/images/figures/gryphon.any.webp', import.meta.url).href,
      width: 480,
      height: 440,
    },
  },
  lobster: {
    any: {
      src: new URL('../../assets/images/figures/lobster.any.webp', import.meta.url).href,
      width: 320,
      height: 240,
    },
  },
  'alices-sister': {
    any: {
      src: new URL('../../assets/images/figures/alices-sister.any.webp', import.meta.url).href,
      width: 600,
      height: 400,
    },
  },
  bill: {
    any: {
      src: new URL('../../assets/images/figures/bill.any.webp', import.meta.url).href,
      width: 240,
      height: 200,
    },
  },
  'guinea-pigs': {
    any: {
      src: new URL('../../assets/images/figures/guinea-pigs.any.webp', import.meta.url).href,
      width: 800,
      height: 240,
    },
  },
  'rose-tree': {
    any: {
      src: new URL('../../assets/images/figures/rose-tree.any.webp', import.meta.url).href,
      width: 640,
      height: 720,
    },
  },
  mushroom: {
    any: {
      src: new URL('../../assets/images/figures/mushroom.any.webp', import.meta.url).href,
      width: 800,
      height: 640,
    },
  },
  hedgehog: {
    any: {
      src: new URL('../../assets/images/figures/hedgehog.any.webp', import.meta.url).href,
      width: 280,
      height: 220,
    },
  },
  'pig-baby': {
    any: {
      src: new URL('../../assets/images/figures/pig-baby.any.webp', import.meta.url).href,
      width: 400,
      height: 400,
    },
  },
  'pig/trotting': {
    any: {
      src: new URL('../../assets/images/figures/pig--trotting.any.webp', import.meta.url).href,
      width: 400,
      height: 280,
    },
  },
  crab: {
    any: {
      src: new URL('../../assets/images/figures/crab.any.webp', import.meta.url).href,
      width: 400,
      height: 240,
    },
  },
  'conger-eel': {
    any: {
      src: new URL('../../assets/images/figures/conger-eel.any.webp', import.meta.url).href,
      width: 600,
      height: 400,
    },
  },
  'dancer/seal': {
    any: {
      src: new URL('../../assets/images/figures/dancer--seal.any.webp', import.meta.url).href,
      width: 280,
      height: 280,
    },
  },
  'dancer/turtle': {
    any: {
      src: new URL('../../assets/images/figures/dancer--turtle.any.webp', import.meta.url).href,
      width: 280,
      height: 280,
    },
  },
  'dancer/salmon': {
    any: {
      src: new URL('../../assets/images/figures/dancer--salmon.any.webp', import.meta.url).href,
      width: 280,
      height: 280,
    },
  },
  'dancer/whiting': {
    any: {
      src: new URL('../../assets/images/figures/dancer--whiting.any.webp', import.meta.url).href,
      width: 280,
      height: 280,
    },
  },
  'dancer/snail': {
    any: {
      src: new URL('../../assets/images/figures/dancer--snail.any.webp', import.meta.url).href,
      width: 280,
      height: 280,
    },
  },
  'dancer/porpoise': {
    any: {
      src: new URL('../../assets/images/figures/dancer--porpoise.any.webp', import.meta.url).href,
      width: 280,
      height: 280,
    },
  },
};

export const BAKED_PARTS: Record<string, { base: Sources; parts: Record<string, Sources> }> = {
  flamingo: {
    base: {
      yellow: {
        src: new URL('../../assets/images/figures/flamingo~base.yellow.webp', import.meta.url).href,
        width: 600,
        height: 840,
      },
      blue: {
        src: new URL('../../assets/images/figures/flamingo~base.blue.webp', import.meta.url).href,
        width: 600,
        height: 840,
      },
    },
    parts: {
      'cq__flamingo-body': {
        any: {
          src: new URL(
            '../../assets/images/figures/flamingo~cq__flamingo-body.any.webp',
            import.meta.url,
          ).href,
          width: 600,
          height: 840,
        },
      },
      'cq__flamingo-head': {
        any: {
          src: new URL(
            '../../assets/images/figures/flamingo~cq__flamingo-head.any.webp',
            import.meta.url,
          ).href,
          width: 600,
          height: 840,
        },
      },
    },
  },
  hedgehog: {
    base: {
      any: {
        src: new URL('../../assets/images/figures/hedgehog~base.any.webp', import.meta.url).href,
        width: 280,
        height: 220,
      },
    },
    parts: {
      'cq__hedgehog-ball': {
        any: {
          src: new URL(
            '../../assets/images/figures/hedgehog~cq__hedgehog-ball.any.webp',
            import.meta.url,
          ).href,
          width: 280,
          height: 220,
        },
      },
      'cq__hedgehog-walk': {
        any: {
          src: new URL(
            '../../assets/images/figures/hedgehog~cq__hedgehog-walk.any.webp',
            import.meta.url,
          ).href,
          width: 280,
          height: 220,
        },
      },
    },
  },
  'gardener/two': {
    base: {
      any: {
        src: new URL('../../assets/images/figures/gardener--two~base.any.webp', import.meta.url)
          .href,
        width: 240,
        height: 440,
      },
    },
    parts: {
      cq__brush: {
        any: {
          src: new URL(
            '../../assets/images/figures/gardener--two~cq__brush.any.webp',
            import.meta.url,
          ).href,
          width: 240,
          height: 440,
        },
      },
    },
  },
  'gardener/five': {
    base: {
      any: {
        src: new URL('../../assets/images/figures/gardener--five~base.any.webp', import.meta.url)
          .href,
        width: 240,
        height: 440,
      },
    },
    parts: {
      cq__brush: {
        any: {
          src: new URL(
            '../../assets/images/figures/gardener--five~cq__brush.any.webp',
            import.meta.url,
          ).href,
          width: 240,
          height: 440,
        },
      },
    },
  },
  'gardener/seven': {
    base: {
      any: {
        src: new URL('../../assets/images/figures/gardener--seven~base.any.webp', import.meta.url)
          .href,
        width: 240,
        height: 440,
      },
    },
    parts: {
      cq__brush: {
        any: {
          src: new URL(
            '../../assets/images/figures/gardener--seven~cq__brush.any.webp',
            import.meta.url,
          ).href,
          width: 240,
          height: 440,
        },
      },
    },
  },
  hatter: {
    base: {
      any: {
        src: new URL('../../assets/images/figures/hatter~base.any.webp', import.meta.url).href,
        width: 320,
        height: 520,
      },
    },
    parts: {
      hatter__hat: {
        any: {
          src: new URL('../../assets/images/figures/hatter~hatter__hat.any.webp', import.meta.url)
            .href,
          width: 320,
          height: 520,
        },
      },
    },
  },
  'guinea-pig': {
    base: {
      any: {
        src: new URL('../../assets/images/figures/guinea-pig~base.any.webp', import.meta.url).href,
        width: 240,
        height: 208,
      },
    },
    parts: {
      'guinea-pig__paw': {
        any: {
          src: new URL(
            '../../assets/images/figures/guinea-pig~guinea-pig__paw.any.webp',
            import.meta.url,
          ).href,
          width: 240,
          height: 208,
        },
      },
    },
  },
  'tortoise-master': {
    base: {
      any: {
        src: new URL('../../assets/images/figures/tortoise-master~base.any.webp', import.meta.url)
          .href,
        width: 400,
        height: 480,
      },
    },
    parts: {
      art__cane: {
        any: {
          src: new URL(
            '../../assets/images/figures/tortoise-master~art__cane.any.webp',
            import.meta.url,
          ).href,
          width: 400,
          height: 480,
        },
      },
    },
  },
};
