/**
 * Generated by scripts/bake-art.mjs (`npm run art:bake`); do not edit by hand.
 * The registry's vectors rendered through the engraved treatment, one picture per
 * Alice variant for Alice and one for anyone else. See docs/art-trials.md.
 */

import type { ImageSource } from './registry.ts';

export const BAKED: Record<string, Partial<Record<'blue' | 'yellow' | 'any', ImageSource>>> = {
  'alice/falling': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--falling.yellow.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--falling.blue.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
  },
  'alice/running-away': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--running-away.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--running-away.blue.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
  },
  'alice/from-behind': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--from-behind.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--from-behind.blue.webp', import.meta.url)
        .href,
      width: 240,
      height: 440,
    },
  },
  'alice/looking-down': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--looking-down.yellow.webp', import.meta.url)
        .href,
      width: 800,
      height: 440,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--looking-down.blue.webp', import.meta.url)
        .href,
      width: 800,
      height: 440,
    },
  },
  'alice/foot': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--foot.yellow.webp', import.meta.url).href,
      width: 400,
      height: 520,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--foot.blue.webp', import.meta.url).href,
      width: 400,
      height: 520,
    },
  },
  'alice/hand-left': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--hand-left.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 400,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--hand-left.blue.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
  },
  'alice/hand-right': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--hand-right.yellow.webp', import.meta.url)
        .href,
      width: 240,
      height: 400,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--hand-right.blue.webp', import.meta.url).href,
      width: 240,
      height: 400,
    },
  },
  'alice/standing': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--standing.yellow.webp', import.meta.url).href,
      width: 160,
      height: 220,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--standing.blue.webp', import.meta.url).href,
      width: 160,
      height: 220,
    },
  },
  'alice/kneeling': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--kneeling.yellow.webp', import.meta.url).href,
      width: 460,
      height: 460,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--kneeling.blue.webp', import.meta.url).href,
      width: 460,
      height: 460,
    },
  },
  'alice/filling': {
    yellow: {
      src: new URL('../../assets/images/figures/alice--filling.yellow.webp', import.meta.url).href,
      width: 1440,
      height: 660,
    },
    blue: {
      src: new URL('../../assets/images/figures/alice--filling.blue.webp', import.meta.url).href,
      width: 1440,
      height: 660,
    },
  },
  'white-rabbit/herald': {
    any: {
      src: new URL('../../assets/images/figures/white-rabbit--herald.any.webp', import.meta.url)
        .href,
      width: 280,
      height: 440,
    },
  },
  'white-rabbit/garden': {
    any: {
      src: new URL('../../assets/images/figures/white-rabbit--garden.any.webp', import.meta.url)
        .href,
      width: 120,
      height: 160,
    },
  },
  'queen-of-hearts': {
    any: {
      src: new URL('../../assets/images/figures/queen-of-hearts.any.webp', import.meta.url).href,
      width: 320,
      height: 480,
    },
  },
  'king-of-hearts': {
    any: {
      src: new URL('../../assets/images/figures/king-of-hearts.any.webp', import.meta.url).href,
      width: 320,
      height: 480,
    },
  },
  'knave-of-hearts': {
    any: {
      src: new URL('../../assets/images/figures/knave-of-hearts.any.webp', import.meta.url).href,
      width: 280,
      height: 440,
    },
  },
  'card-soldier': {
    any: {
      src: new URL('../../assets/images/figures/card-soldier.any.webp', import.meta.url).href,
      width: 240,
      height: 440,
    },
  },
  'card-arch': {
    any: {
      src: new URL('../../assets/images/figures/card-arch.any.webp', import.meta.url).href,
      width: 400,
      height: 280,
    },
  },
  duchess: {
    any: {
      src: new URL('../../assets/images/figures/duchess.any.webp', import.meta.url).href,
      width: 480,
      height: 520,
    },
  },
  cook: {
    any: {
      src: new URL('../../assets/images/figures/cook.any.webp', import.meta.url).href,
      width: 400,
      height: 520,
    },
  },
  'march-hare': {
    any: {
      src: new URL('../../assets/images/figures/march-hare.any.webp', import.meta.url).href,
      width: 320,
      height: 520,
    },
  },
  dormouse: {
    any: {
      src: new URL('../../assets/images/figures/dormouse.any.webp', import.meta.url).href,
      width: 280,
      height: 220,
    },
  },
  'mock-turtle': {
    any: {
      src: new URL('../../assets/images/figures/mock-turtle.any.webp', import.meta.url).href,
      width: 480,
      height: 440,
    },
  },
  gryphon: {
    any: {
      src: new URL('../../assets/images/figures/gryphon.any.webp', import.meta.url).href,
      width: 480,
      height: 440,
    },
  },
  lobster: {
    any: {
      src: new URL('../../assets/images/figures/lobster.any.webp', import.meta.url).href,
      width: 320,
      height: 240,
    },
  },
  'alices-sister': {
    any: {
      src: new URL('../../assets/images/figures/alices-sister.any.webp', import.meta.url).href,
      width: 600,
      height: 400,
    },
  },
  bill: {
    any: {
      src: new URL('../../assets/images/figures/bill.any.webp', import.meta.url).href,
      width: 240,
      height: 200,
    },
  },
  'guinea-pigs': {
    any: {
      src: new URL('../../assets/images/figures/guinea-pigs.any.webp', import.meta.url).href,
      width: 800,
      height: 240,
    },
  },
  'rose-tree': {
    any: {
      src: new URL('../../assets/images/figures/rose-tree.any.webp', import.meta.url).href,
      width: 640,
      height: 720,
    },
  },
  mushroom: {
    any: {
      src: new URL('../../assets/images/figures/mushroom.any.webp', import.meta.url).href,
      width: 800,
      height: 640,
    },
  },
};
